# Generated by Django 3.1.5 on 2021-01-31 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0002_remove_car_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='carmake',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='car',
            name='carmodel',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.DeleteModel(
            name='CarMake',
        ),
        migrations.DeleteModel(
            name='CarModel',
        ),
    ]
