# Generated by Django 3.1.5 on 2021-01-31 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0003_auto_20210131_0025'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='rating',
            field=models.IntegerField(default=0),
        ),
    ]
