# Generated by Django 3.1.5 on 2021-02-02 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0004_car_rating'),
    ]

    operations = [
        migrations.CreateModel(
            name='rating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate_num', models.IntegerField(default=0)),
            ],
        ),
        migrations.RemoveField(
            model_name='car',
            name='rating',
        ),
        migrations.AddField(
            model_name='car',
            name='rating',
            field=models.ManyToManyField(to='car.rating'),
        ),
    ]
