# Generated by Django 3.1.5 on 2021-02-02 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0005_auto_20210202_0143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='rating',
            field=models.ManyToManyField(to='car.Rating'),
        ),
    ]
