# Generated by Django 3.1.5 on 2021-02-02 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0006_auto_20210202_0144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='rating',
            field=models.ManyToManyField(default=0, to='car.Rating'),
        ),
    ]
